meilisearch:
    url: 'http://%env(MEILISEARCH_LISTEN_IP)%:%env(MEILISEARCH_LISTEN_PORT)%:' # URL of the Meilisearch server (mandatory)
    api_key: '%env(MEILISEARCH_API_KEY)%' # API key to access the Meilisearch server (mandatory)
    prefix: '%env(MEILISEARCH_PREFIX)%'
    indices:
        # Define entities or documents that should be indexed to Meilisearch.
        # See https://github.com/meilisearch/meilisearch-symfony/wiki/configure-searchable-data
        - name: posts
          class: App\Entity\Post
          settings:
              filterableAttributes:
                  - created_at
                  - title
              searchableAttributes:
                  - description
              sortableAttributes:
                  - time
