services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb
      - meilisearch
    networks:
      - app-network

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  meilisearch:
    image: getmeili/meilisearch:v1.14
    container_name: meilisearch
    env_file:
      - .env
    ports:
      - "${MEILISEARCH_LISTEN_IP}:${MEILISEARCH_LISTEN_PORT}:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_API_KEY}
    volumes:
      - meilisearch_data:/meili_data
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  meilisearch_data:
